### ISSUE TITLE
Deploying the model for Inference

### ISSUE THREAD

**Issue by gitvicky** [PolymathicAI/multiple_physics_pretraining#1]
Hi, 

Would you be able to provide python script that can perform inference over one of the pre-trained models with one of the datasets that the code/model has been validated on ?

**Comment by mikemccabe210** [comment]
Hi,

Could you post the actual error/stack trace that you're getting? Those should be in the right format, but I remember we needed to make some edits to the text strings to make them work with the new instructions (the old process was much more labor intensive). It's possible something didn't make it over to the public code, but I'll need to look into where it's currently going wrong.

**Comment by gitvicky** [comment]
Hi, 

So I have been able to setup the pre-training pipeline following the instructions that you had given. I was trying to set up the model under the _finetune_ config and got this error: 

`(.venv) Vicky@Vigneshs-Macbook Polymathic_CP % python train_basic.py --yaml_config config/mpp_avit_ti_config.yaml --config finetune

Initializing data on rank 0
Initializing model on rank 0
Model parameter count: 7285884
Starting from pretrained model at ~/Polymathic_CP/weights/MPP_AViT_Ti
Traceback (most recent call last):
  File "~/Polymathic_CP/train_basic.py", line 551, in <module>
    trainer = Trainer(params, global_rank, local_rank, device, sweep_id=args.sweep_id)
  File "~/Polymathic_CP/train_basic.py", line 80, in __init__
    self.restore_checkpoint(params.pretrained_ckpt_path)
  File "~/Polymathic_CP/train_basic.py", line 205, in restore_checkpoint
    self.model.module.unfreeze()
  File "~/Polymathic_CP/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'AViT' object has no attribute 'module'
`

Could you check to see whether the shared model weights are in the right format ? Or is it that I might have missed something. 


Thanks, 
Vignesh

**Comment by gitvicky** [comment]
Thanks. That worked a charm. I have done a fix for this and you can find it here: https://github.com/gitvicky/multiple_physics_pretraining/blob/csd3/train_basic.py

**Comment by gitvicky** [comment]
Was working on setting up the model for inference initially and noticed this unusual artefacts popping up on the model outputs. I have provided the visualisation of the model output and the expected model target here: 

![model_out](https://github.com/PolymathicAI/multiple_physics_pretraining/assets/28906480/120299a0-acb7-47bc-ba7a-f423ccf010f5)
![model_targ](https://github.com/PolymathicAI/multiple_physics_pretraining/assets/28906480/43a6aee4-277e-4f86-9f8a-6dc17973367d)


I had only slightly modified your train_basic file to set it up for inference across trained models. The inference code can be found here: https://github.com/gitvicky/multiple_physics_pretraining/blob/b4f39c11c87df098bc3d79f767f6746a325daf83/test_basic.py#L379

**Comment by mikemccabe210** [comment]
Thanks for finding this! Since this discussion happened offline, for anyone reading this later the early patching was the result of a bug in the bias copy for finetuning. This was fixed in 462d2992b74563c0325d2ec8baf8cd8e7952b0bc so closing the issue.
